schema_version: 1.0
session: redsun-mimir
frontend: pyqt

devices:
  camera1:
    config: demo
  xy-motor:
    config: demoxy
  z-motor:
    config: demoz

presenters:
  storage_ctrl: {}
  median_ctrl:
    median_streams: [square_scan]
    live_streams: [live]
    hints: [buffer]
  det_ctrl:
    timeout: 5.0
  acq_ctrl:
    callbacks: [det_ctrl, median_ctrl]

views:
  acq_widget: {}
  img_widget: {}
  det_widget: {}
  storage_widget: {}
