schema_version: 1.0
session: redsun-mimir
frontend: pyqt

devices:
  camera1: {}
  xy-motor: {}
  z-motor: {}

presenters:
  storage_ctrl: {}
  median_ctrl: {}
  det_ctrl:
    timeout: 5.0
  acq_ctrl: {}

views:
  acq_widget: {}
  img_widget: {}
  det_widget: {}
  storage_widget: {}
