schema_version: 1.0
session: redsun-mimir
frontend: pyqt

devices:
  camera1: {}
  xy-motor: {}
  z-motor: {}
  led:
    wavelength: 300
  laser:
    wavelength: 650

presenters:
  storage_ctrl: {}
  median_ctrl: {}
  det_ctrl:
    timeout: 2.0
  acq_ctrl: {}
  light_ctrl:
    timeout: 2.0
  motor_ctrl:
    timeout: 2.0


views:
  light_widget: {}
  motor_widget: {}
  acq_widget: {}
  img_widget: {}
  det_widget: {}
  storage_widget: {}
