session: redsun-mimir
engine: bluesky
frontend: pyqt
widgets:
  ImageWidget:
    plugin_name: test
    plugin_id: test
    # doesn't have any effect;
    # used locally for testing
    position: center
