# UC2 hardware. Lays over common_configuration.yaml.

services:
  transport: pv-access
  camera_ioc:
    plugin_name: redsun-mimir
    plugin_id: mmcore-camera
    prefix: "MIMIR-ISCAT:"
    args: ["--adapter", "DahengGalaxy", "--device", "DahengCamera"]
  uc2_board:
    plugin_name: redsun-mimir
    plugin_id: youseetoo-controller
    prefix: "MIMIR-UC2:"
    args: ["--port", "COM4"]

devices:
  laser:
    wavelength: 650
