# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.0
_src_path: https://github.com/redsun-acquisition/redsun-plugin-template
add_widget: true
class_baseline: StageController
email: jacopo.abramo@gmail.com
full_name: Jacopo Abramo
github_repository_url: https://github.com/redsun-acquisition/redsun-mimir
github_username_or_organization: redsun-acquisition
install_precommit: true
license: Apache Software License 2.0
module_name: redsun_mimir
plugin_name: redsun-mimir
plugin_type: Controller
short_description: Plugin bundle for the OpenUC2 "Mimir" microscope
widget_class_baseline: StageWidget
