models:
controllers:
  stage:
    class: redsun_mimir.controller:MotorController
    info: redsun_mimir.controller:MotorControllerInfo
views:
  stage:
    class: redsun_mimir.widget:MotorWidget
    info: redsun_mimir.widget:StageWidgetInfo
