models:
controllers:
  stage:
    class: redsun_mimir.controller:StageController
    info: redsun_mimir.controller:StageControllerInfo
views:
  stage:
    class: redsun_mimir.widget:StageWidget
    info: redsun_mimir.widget:StageWidgetInfo
