devices:
  # mimir models
  mimir-serial: redsun_mimir.device.youseetoo:MimirSerialDevice
  mimir-motor: redsun_mimir.device.youseetoo:MimirMotorDevice
  mimir-laser: redsun_mimir.device.youseetoo:MimirLaserDevice

  # microscope/mock models
  mock-light: redsun_mimir.device:MockLightDevice
  mock-motor: redsun_mimir.device:MockMotorDevice
  mock-detector: redsun_mimir.device.microscope:SimulatedCameraDevice
  mmcore-camera: redsun_mimir.device.mmcore:MMCoreCameraDevice

presenters:
  acquisition: redsun_mimir.presenter:AcquisitionPresenter
  motor: redsun_mimir.presenter:MotorPresenter
  light: redsun_mimir.presenter:LightPresenter
  detector: redsun_mimir.presenter:DetectorPresenter
  median: redsun_mimir.presenter:MedianPresenter

views:
  acquisition: redsun_mimir.view:AcquisitionView
  image: redsun_mimir.view:ImageView
  detector: redsun_mimir.view:DetectorView
  motor: redsun_mimir.view:MotorView
  light: redsun_mimir.view:LightView
