devices:
  # youseetoo (UC2) devices
  uc2-motor: redsun_mimir.device.youseetoo:UC2MotorDevice
  uc2-laser: redsun_mimir.device.youseetoo:UC2LaserDevice

  # mmcore devices
  mmcore-camera: redsun_mimir.device.mmcore:MMCamera
  mmcore-stage: redsun_mimir.device.mmcore:MMStage

  # mock devices
  mock-light: redsun_mimir.device:MockLightDevice

services:
  mmcore-camera:
    module: redsun_mimir.services.mmcore_camera
    ready: mmcore camera ready
  mmcore-stage:
    module: redsun_mimir.services.mmcore_stage
    ready: mmcore stage ready
  youseetoo-controller:
    module: redsun_mimir.services.uc2_controller
    ready: uc2 controller ready

presenters:
  acquisition: redsun_mimir.presenter.acquisition:AcquisitionPresenter
  motor: redsun_mimir.presenter.motor:MotorPresenter
  light: redsun_mimir.presenter.light:LightPresenter
  detector: redsun_mimir.presenter.detector:DetectorPresenter
  median: redsun_mimir.presenter.median:MedianPresenter

views:
  acquisition: redsun_mimir.view.acquisition:AcquisitionView
  image: redsun_mimir.view.image:ImageView
  detector: redsun_mimir.view.detector:DetectorView
  motor: redsun_mimir.view.motor:MotorView
  light: redsun_mimir.view.light:LightView
