devices:
  # youseetoo (UC2) devices
  uc2-serial: redsun_mimir.device.youseetoo:UC2Serial
  uc2-motor: redsun_mimir.device.youseetoo:UC2MotorDevice
  uc2-laser: redsun_mimir.device.youseetoo:UC2LaserDevice

  # mmcore devices
  mmcore-demo-camera: redsun_mimir.device.mmcore:MMDemoCamera
  mmcore-daheng-camera: redsun_mimir.device.mmcore:MMDahengCamera
  mmcore-demo-xy-stage: redsun_mimir.device.mmcore:MMDemoXYStage
  mmcore-demo-z-stage: redsun_mimir.device.mmcore:MMDemoZStage

  # mock devices
  mock-light: redsun_mimir.device:MockLightDevice

presenters:
  acquisition: redsun_mimir.presenter.acquisition:AcquisitionPresenter
  motor: redsun_mimir.presenter.motor:MotorPresenter
  light: redsun_mimir.presenter.light:LightPresenter
  detector: redsun_mimir.presenter.detector:DetectorPresenter
  median: redsun_mimir.presenter.median:MedianPresenter

views:
  acquisition: redsun_mimir.view.acquisition:AcquisitionView
  image: redsun_mimir.view.image:ImageView
  detector: redsun_mimir.view.detector:DetectorView
  motor: redsun_mimir.view.motor:MotorView
  light: redsun_mimir.view.light:LightView
