models:
  # mimir models
  mimir-serial:
    class: redsun_mimir.model.youseetoo:MimirSerialModel
    info: redsun_mimir.model.youseetoo:MimirSerialModelInfo
  mimir-motor:
    class: redsun_mimir.model.youseetoo:MimirMotorModel
    info: redsun_mimir.model:MotorModelInfo
  mimir-laser:
    class: redsun_mimir.model.youseetoo:MimirLaserModel
    info: redsun_mimir.model:LaserModelInfo

  # microscope/mock models
  mock-light:
    class: redsun_mimir.model:MockLightModel
    info: redsun_mimir.model:LightModelInfo
  mock-motor:
    class: redsun_mimir.model:MockMotorModel
    info: redsun_mimir.model:MotorModelInfo
  mock-detector:
    class: redsun_mimir.model.microscope:SimulatedCameraModel
    info: redsun_mimir.model:DetectorModelInfo

controllers:
  acquisition:
    class: redsun_mimir.controller:AcquisitionController
    info: redsun_mimir.controller:AcquisitionControllerInfo
  motor:
    class: redsun_mimir.controller:MotorController
    info: redsun_mimir.controller:MotorControllerInfo
  light:
    class: redsun_mimir.controller:LightController
    info: redsun_mimir.controller:LightControllerInfo
  detector:
    class: redsun_mimir.controller:DetectorController
    info: redsun_mimir.controller:DetectorControllerInfo

views:
  acquisition:
    class: redsun_mimir.widget:AcquisitionWidget
    info: redsun_mimir.widget:AcquisitionWidgetInfo
  motor:
    class: redsun_mimir.widget:MotorWidget
    info: redsun_mimir.widget:MotorWidgetInfo
  light:
    class: redsun_mimir.widget:LightWidget
    info: redsun_mimir.widget:LightWidgetInfo
  detector:
    class: redsun_mimir.widget:DetectorWidget
    info: redsun_mimir.widget:DetectorWidgetInfo
