devices:
  # mimir models
  mimir-serial:
    class: redsun_mimir.device.youseetoo:MimirSerialDevice
  mimir-motor:
    class: redsun_mimir.device.youseetoo:MimirMotorDevice
  mimir-laser:
    class: redsun_mimir.device.youseetoo:MimirLaserDevice
    info: redsun_mimir.device:LaserModelInfo

  # microscope/mock models
  mock-light:
    class: redsun_mimir.device:MockLightDevice
  mock-motor:
    class: redsun_mimir.device:MockMotorDevice
  mock-detector:
    class: redsun_mimir.device.microscope:SimulatedCameraModel

presenters:
  acquisition:
    class: redsun_mimir.presenter:AcquisitionController
  motor:
    class: redsun_mimir.presenter:MotorController
  light:
    class: redsun_mimir.presenter:LightController
  detector:
    class: redsun_mimir.presenter:DetectorController

views:
  acquisition:
    class: redsun_mimir.view:AcquisitionWidget
  motor:
    class: redsun_mimir.view:MotorWidget
  light:
    class: redsun_mimir.view:LightWidget
  detector:
    class: redsun_mimir.view:DetectorWidget
